baseURL: https://joyemery.art
title: Joy Emery's Art
defaultContentLanguage: "en"
theme: eternity
googleAnalytics: "" # todo: set your analytics id.

params:
  image: /images/banner.jpg
  logo: /images/logo.png
  subtitle: Art made in joy. # todo: change default subtitle for your website.
  copyright: All rights reserved.
  author: Joy Emery
  dontShowSource: true
  multipleColumn: true
  portfolio:
    columns:
      desktop:
        default: 3
      mobile:
        default: 2
  socials:
  homepage: "/highlights"
  specialPages:
    - highlights
    - art
  bypassWelcomePage: false # redirects "/" to "homepage" when it's true.
  plausible: "" # todo: set your plausible id.
  disableRadius: false
  moveIt: false # Moves Title and Meta info down, only visible when scroll.

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags
  medium: media

permalinks:
  tags: ":slug"
  media: "/media/:slug"

menu:
  main:
    - name: Highlights
      url: /highlights/
      weight: 1
    - name: Medieval
      url: /medieval/
      weight: 2
    - name: Nature
      url: /nature/
      weight: 3
    - name: Fairy Tale
      url: /fairy-tale/
      weight: 4
    - name: Installations
      url: /installations/
      weight: 5
    - name: Stationary
      url: /stationary/
      weight: 6
    - name: Media
      url: /media/
      weight: 95
    - name: All Art
      url: /art/
      weight: 100
