baseURL: https://joyemery.art
title: Joy Emery's Art
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: '' # todo: set your analytics id.

params:
  image: /images/banner.png
  subtitle: Many media. # todo: change default subtitle for your website.
  copyright: All rights reserved.
  author: Joy Emery
  dontShowSource: true
  portfolio:
    columns:
      desktop:
        default: 3
      mobile:
        default: 2
  socials:
    # todo: change these links.
    - icon: 'far fa-envelope fa-lg'
      url: 'mailto:joyemery@gmail.com'
      landing: true
    # - icon: 'fab fa-instagram fa-lg'
    #   url: 'https://instagram.com/joyemery'
  homepage: "/highlights"
  specialPages:
    - highlights
    - art
  bypassWelcomePage: true # redirects "/" to "homepage" when it's true.
  plausible: '' # todo: set your plausible id.
  disableRadius: false
  moveIt: false  # Moves Title and Meta info down, only visible when scroll.

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags
  medium: media

permalinks:
  tags: ":slug"
  media: "/media/:slug"

menu:
  main:
    - name: Highlights
      url: /highlights/
      weight: 1
    - name: Midieval
      url: /midieval/
      weight: 2
    - name: Nature
      url: /nature/
      weight: 3
    # - name: Media
    #   url: /media/
    #   weight: 4
    - name: All Art
      url: /art/
      weight: 5
