services:
  - type: web
    name: joyemery-art
    env: static
    buildCommand: npm run build
    staticPublishPath: public
    pullRequestPreviewsEnabled: true # optional
    # headers:
    #   - path: /*
    #     name: X-Frame-Options
    #     value: sameorigin
    # routes:
    #   - type: redirect
    #     source: /old
    #     destination: /new
    #   - type: rewrite
    #     source: /a/*
    #     destination: /a
